#include <iostream.h>
#include <stdio.h>
#include <conio.h>
#include <dos.h>
    int main()
{ for(int i=1;i<=2;i++)
  { sound(220);
   delay(100);

   nosound();
   delay(100);

   sound(220);
   delay(100);

     nosound();

   sound(220);
   delay(100);

   sound(261.7);
   delay(100);

    sound(246.9);
   delay(100);

   sound(220);
   delay(100);

   sound(329.6);
   delay(100);
     nosound();
     delay(100);

   sound(164.8);
   delay(100) ;
      nosound();

   sound(164.8);
   delay(100) ;
    nosound();

   sound(207.7);
   delay(100) ;

    sound(185);
    delay(100) ;

   sound(164.8);
   delay(100) ;

      sound(220);
      delay(100);
	  nosound()    ;
	  delay(100);

      sound(220);
      delay(100);
	   nosound();

      sound(220);
      delay(100);

      sound(261.7);
      delay(100);

      sound(246.9);
      delay(100) ;

    sound(220);
    delay(100) ;

   sound(329.6);
   delay(200) ;
    nosound();
   delay(100);

   sound(164.8);
   delay(200) ;
     nosound();
    delay(200);    };

//////////////////////////////////////////////


////////////////////////////////////////////
    sound(440);
    delay(100);
    nosound();
      delay(100);

    sound(440);
    delay(100);

    nosound();

    sound(440);
    delay(100);

    sound(466.2);
    delay(100);

    sound(440);
    delay(100);

    sound(392);
    delay(100);

    sound(349.2);
    delay(100); //bugs
	nosound();
	delay(100);

    sound(293.7);
    delay(100);

       nosound();

    sound(293.7);
    delay(100);

    sound(349.2);
    delay(100);
       nosound();

    sound(329.6);
    delay(100);

    sound(293.7);
    delay(100);

       sound(392);
      delay(100);
	nosound();
	delay(100);
   ///3takt
	sound(392);
	delay(100);

	 nosound();

	sound(392);
	 delay(100);

	sound(440);
	delay(100);

	sound(392);
	delay(100);

	sound(349.2);
	delay(100);

	sound(329.6);
	delay(100);
	nosound();
	delay(100);
////////////////4takt
	sound(261.7);
	delay(100);
	nosound()   ;

	sound(261.7);
	delay(100);

	sound(329.6);
	delay(100);

	sound(293.7);
	delay(100);

	sound(261.7);
	delay(100);

	sound(349.2);
	delay(100);
	nosound();
	delay(100);

	sound(246.9);
	delay(100);
	nosound();

	sound(246.9);
	delay(100);

	sound(293.7);
	delay(100);

	sound(261.7);
	delay(100);

       sound(246.9);
	delay(100);

	sound(329.6);
	delay(100);
	 nosound();
	 delay(100);

       sound(220);
	delay(100);
       nosound();

       sound(220);
	delay(100);

       sound(261.7);
	delay(100);

       sound(246.9);
	delay(100);

       sound(220);
	delay(100);

      sound(174.6);
	delay(100);

      nosound();
      delay(100);

      sound(311.1);
      delay(100);

      sound(164.8);
      delay(100);
	nosound();
	delay(100);

      sound(329.6);
	delay(100);

       sound(293.7);
	delay(100);

       sound(246.9);
	delay(100);

       sound(220);
	delay(100);

      sound(110);
      delay(200);

	       
  nosound();
   getch();
    return 0;
}
